### ISSUE TITLE
Bug with sanitizing html in title

### ISSUE THREAD

**Issue by jfroelich** [jfroelich/rss-reader#449]
The entry with the url https://shkspr.mobi/blog/2017/11/input-type-country/. This completely got through the filters. How?

Issue: the title attribute value contains `<input type="“country”">`. This shouldn't happen.
Two: the value of the entry title displayed in the slideshow contains unsafe html: `<a href="https://shkspr.mobi/blog/2017/11/input-type-country/" class="entry-title" target="_blank" rel="noreferrer" title="<input type=&quot;“country”&quot;>"><input type="“country”"></a>`

Viewing source of remote web page, title is `<title>&lt;input type=&#8221;country&#8221; /&gt; &#8211; Terence Eden&#039;s Blog</title>`

**Comment by jfroelich** [comment]
Done

**Comment by edent** [comment]
Sorry for breaking things :-)
