### ISSUE TITLE
New Logo for RSS Reader

### ISSUE THREAD

**Issue by Yasujizr** [jfroelich/rss-reader#537]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a icon.

Best Regards.

**Comment by jfroelich** [comment]
You are welcome to design an icon.

**Comment by jfroelich** [comment]
Nice job. It would be preferable to not include text because the name is likely to change.

**Comment by Yasujizr** [comment]
Thank you, which sizes and formats do you need? I can also do a Banner to appear on the Google Extensions page.

Can I send you a PR to be included in Read.me?

**Comment by jfroelich** [comment]
Hmm. Still new to collaborating with others on github, so I need some help here. Just tell me what I should do to let you bring in your changes. So yes you can send me a PR but I am not totally sure how to use it and need some help there.

I think I would need all the sizes/formats that Chrome asks for extensions? I cannot remember but I think there are some notes somewhere in the extensions documentation on which icons should be present. It is up to you.

**Comment by jfroelich** [comment]
Docs on icons from https://developer.chrome.com/extensions/manifest/icons

I am not sure at the moment about putting it in the store.

**Comment by Yasujizr** [comment]
I sent a PR.

**Comment by jfroelich** [comment]
Seems like it works! I am going to leave this open until I properly update the extension configuration to make use of the new icons.

Thank you for contributing.

**Comment by jfroelich** [comment]
Icons integrated.

**Comment by Yasujizr** [comment]
Thank you. I hope you continue to support the open source. :)
